# Generated by Django 4.2 on 2023-04-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='Due_Date',
            field=models.DateField(null=True),
        ),
    ]
