# Generated by Django 4.2 on 2023-04-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0002_assignments_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='Subject_Status',
        ),
        migrations.AddField(
            model_name='assignments',
            name='Submit_Status',
            field=models.CharField(default='Not Submitted', max_length=20),
        ),
    ]
